apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dakuworks-dev

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- postgres.yaml
- redis.yaml

commonLabels:
  app.kubernetes.io/name: dakuworks
  app.kubernetes.io/part-of: dakuworks
  app.kubernetes.io/managed-by: argocd
